apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: ap44uz5nk-nodejs-gitops
  description: This is GitOps manifest for ap44uz5nk-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: ap44uz5nk-nodejs
    backstage.io/kubernetes-id: ap44uz5nk-nodejs 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: ap44uz5nk-nodejs   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:ap44uz5nk-nodejs
