apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ap44uz5nk-nodejs
  janus-idp.io/tekton: ap44uz5nk-nodejs
  backstage.io/kubernetes-id: ap44uz5nk-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ap44uz5nk-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
